# Generated by Django 5.2.5 on 2025-08-22 10:17

import django.db.models.deletion
import django.db.models.deletion
from django.db import migrations, models

BRANDS = [
    'Toyota', 'Volkswagen', 'Hyundai', 'Ford', 'Honda', 'Chevrolet', 'Kia',
    'Nissan', 'BYD', 'Mercedes-Benz', 'BMW', 'Stellantis', 'Suzuki', 'Geely',
    'Audi', 'Tesla', 'Renault', 'Mazda', 'Subaru', 'GMC'
]


def create_brands(apps, schema_editor):
    brand = apps.get_model('SmartDjango', 'Brand')
    for name in BRANDS:
        brand.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('SmartDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='SmartDjango.brand'),
        ),
        migrations.RunPython(create_brands),
    ]
